### ISSUE TITLE
Balance display error. The wallet has 1000 axe, but displays 0 axe

### ISSUE THREAD

**Issue by TomaNovak** [AXErunners/electrum-axe#27]
Hello, I use an electron wallet to pay the axe I sent a core axe from my own wallet to the electron axe
 connected to the safe. The first trial 1axe payment was passed on request. The second 1000axe payment, according to the explorer, is also sent and credited, but the electron wallet is not shown. The error message: "Axe Electrum was unable to deserialize the transaction: unpack_from requires a buffer of least 4 bytes"
![axe](https://user-images.githubusercontent.com/48328792/53975025-3f594380-4104-11e9-82ff-e917402c6548.png)

**Comment by TomaNovak** [comment]
![my adress](https://user-images.githubusercontent.com/48328792/54025289-5d718300-419a-11e9-8d75-cd79743d5011.png)
![explorer record](https://user-images.githubusercontent.com/48328792/54025301-63fffa80-419a-11e9-8c03-ec2cc60ba5ae.png)
![amount](https://user-images.githubusercontent.com/48328792/54025305-67938180-419a-11e9-98ee-b461861e0a24.png)

**Comment by ddude1** [comment]
Please make sure you are connected to 149.28.61.183. the trx should show up.
