### ISSUE TITLE
Trezor support Firmware v1.8.1

### ISSUE THREAD

**Issue by BlinkVoid** [AXErunners/electrum-axe#40]
Hi team, I've enountered some difficulties in using trezor with the electrum wallet and now I can't access the funds. 

1. Initially, was able to open eletrum wallet with trezor (wallet successfully detected trezor and was able to choose first of the two xpath options to open the wallet.)  - retested with unplug and plug trezor backin, was able to access the wallet using trezor to unlock.
2. Transferred funds in and when I tried to transfer for colleteral (1000AEX per transaction), encountered problem as: "invalid coin name". 
3. Tried to update the firmware to v1.8.1, while the eletrum program was still open. After update, "invalid coin name" error disapeared, and proceeded to sign transaction phase. Here, electrum start to prompt failed to connect with trezor wallet, after several failed attemps in signing the transaction, decided to close eletrum and try redo the transaction. 
4. Encountered same problem when trying to open eletrum: 
![image](https://user-images.githubusercontent.com/3224348/60189029-a0538580-9873-11e9-8b15-1096cc04c744.png)
![image](https://user-images.githubusercontent.com/3224348/60189371-2243ae80-9874-11e9-9e72-d30ca7dd23b1.png)
Any ideas how I can solve this? 

Thanks

**Comment by Kurbeks** [comment]
Does trezor itself work after update? Like in wallet.trezor.io, get's detected?

**Comment by BlinkVoid** [comment]
Yes, it does. Works fine with the website, it can be detected and I can log
into the wallet account.
Do you think it's the firmware?

**Comment by charlesrocket** [comment]
Is there more in debug/logs? My guess this that you driving with webusb and not bridge.

**Comment by BlinkVoid** [comment]
Looks that way, I'll update more details later today.

Planning to test on a different computer as well.

Cheers

**Comment by BlinkVoid** [comment]
> Is there more in debug/logs? My guess you driving with webusb and not bridge.

Exactly like you suspected, trezor switched to webusb. 
Tried on second computer, eletrum successfully read data from Trezor using WebUSB. the signing issue seems to originated from compatibility issue with the older firmware, once updated, it is able to recognise the coin and transact accordingly. 

Will now go ahead and close the issue. 
If you are still interesed with the logs, I'll find it and post it afterwards.
